#ifndef __MT7697_LBLE_CONFIG_HPP__
#define __MT7697_LBLE_CONFIG_HPP__

#include <vector>
#include <LBLEPeriphral.h>
#include <LBLE.h>

const int PIN_MODE_ANALOG_READ   = 0x00;
const int PIN_MODE_ANALOG_WRITE  = 0x01;
const int PIN_MODE_DIGITAL_READ  = 0x02;
const int PIN_MODE_DIGITAL_WRITE = 0x03;
const int PIN_MODE_SERVO         = 0x04;
const int PIN_MODE_NONE          = 0xFF;

// gpio profile struct
struct gpio_lble_profile
{
    int pin;
    int mode;
    LBLEService *service;
    LBLECharacteristicInt *mode_char;
    LBLECharacteristicBuffer *data_char;
};

// TODO I2C impl.
/*
LBLEService I2C_SERVICE();
LBLECharacteristicInt I2C_READ_CHARACTERISTIC();
LBLECharacteristicBuffer I2C_WRITE_CHARACTERISTIC();
*/

static LBLEService GPIO00_SERVICE(GPIO00_SERVICE_UUID);
static LBLECharacteristicInt GPIO00_MODE_CHARACTERISTIC(GPIO00_MODE_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);
static LBLECharacteristicBuffer GPIO00_DATA_CHARACTERISTIC(GPIO00_DATA_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService GPIO02_SERVICE(GPIO02_SERVICE_UUID);
static LBLECharacteristicInt GPIO02_MODE_CHARACTERISTIC(GPIO02_MODE_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);
static LBLECharacteristicBuffer GPIO02_DATA_CHARACTERISTIC(GPIO02_DATA_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService GPIO03_SERVICE(GPIO03_SERVICE_UUID);
static LBLECharacteristicInt GPIO03_MODE_CHARACTERISTIC(GPIO03_MODE_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);
static LBLECharacteristicBuffer GPIO03_DATA_CHARACTERISTIC(GPIO03_DATA_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService GPIO29_SERVICE(GPIO29_SERVICE_UUID);
static LBLECharacteristicInt GPIO29_MODE_CHARACTERISTIC(GPIO29_MODE_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);
static LBLECharacteristicBuffer GPIO29_DATA_CHARACTERISTIC(GPIO29_DATA_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService GPIO30_SERVICE(GPIO30_SERVICE_UUID);
static LBLECharacteristicInt GPIO30_MODE_CHARACTERISTIC(GPIO30_MODE_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);
static LBLECharacteristicBuffer GPIO30_DATA_CHARACTERISTIC(GPIO30_DATA_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService GPIO31_SERVICE(GPIO31_SERVICE_UUID);
static LBLECharacteristicInt GPIO31_MODE_CHARACTERISTIC(GPIO31_MODE_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);
static LBLECharacteristicBuffer GPIO31_DATA_CHARACTERISTIC(GPIO31_DATA_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService GPIO32_SERVICE(GPIO32_SERVICE_UUID);
static LBLECharacteristicInt GPIO32_MODE_CHARACTERISTIC(GPIO32_MODE_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);
static LBLECharacteristicBuffer GPIO32_DATA_CHARACTERISTIC(GPIO32_DATA_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService GPIO33_SERVICE(GPIO33_SERVICE_UUID);
static LBLECharacteristicInt GPIO33_MODE_CHARACTERISTIC(GPIO33_MODE_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);
static LBLECharacteristicBuffer GPIO33_DATA_CHARACTERISTIC(GPIO33_DATA_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService GPIO34_SERVICE(GPIO34_SERVICE_UUID);
static LBLECharacteristicInt GPIO34_MODE_CHARACTERISTIC(GPIO34_MODE_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);
static LBLECharacteristicBuffer GPIO34_DATA_CHARACTERISTIC(GPIO34_DATA_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService GPIO38_SERVICE(GPIO38_SERVICE_UUID);
static LBLECharacteristicInt GPIO38_MODE_CHARACTERISTIC(GPIO38_MODE_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);
static LBLECharacteristicBuffer GPIO38_DATA_CHARACTERISTIC(GPIO38_DATA_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService GPIO39_SERVICE(GPIO39_SERVICE_UUID);
static LBLECharacteristicInt GPIO39_MODE_CHARACTERISTIC(GPIO39_MODE_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);
static LBLECharacteristicBuffer GPIO39_DATA_CHARACTERISTIC(GPIO39_DATA_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService GPIO57_SERVICE(GPIO57_SERVICE_UUID);
static LBLECharacteristicInt GPIO57_MODE_CHARACTERISTIC(GPIO57_MODE_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);
static LBLECharacteristicBuffer GPIO57_DATA_CHARACTERISTIC(GPIO57_DATA_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService GPIO58_SERVICE(GPIO58_SERVICE_UUID);
static LBLECharacteristicInt GPIO58_MODE_CHARACTERISTIC(GPIO58_MODE_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);
static LBLECharacteristicBuffer GPIO58_DATA_CHARACTERISTIC(GPIO58_DATA_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService GPIO59_SERVICE(GPIO59_SERVICE_UUID);
static LBLECharacteristicInt GPIO59_MODE_CHARACTERISTIC(GPIO59_MODE_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);
static LBLECharacteristicBuffer GPIO59_DATA_CHARACTERISTIC(GPIO59_DATA_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService GPIO60_SERVICE(GPIO60_SERVICE_UUID);
static LBLECharacteristicInt GPIO60_MODE_CHARACTERISTIC(GPIO60_MODE_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);
static LBLECharacteristicBuffer GPIO60_DATA_CHARACTERISTIC(GPIO60_DATA_CHARACTERISTIC_UUID, LBLE_READ | LBLE_WRITE);

static gpio_lble_profile GPIO_LBLE_PROFILES[] = {
    { 00,
      PIN_MODE_NONE,
      &GPIO00_SERVICE,
      &GPIO00_MODE_CHARACTERISTIC,
      &GPIO00_DATA_CHARACTERISTIC },
    { 02,
      PIN_MODE_NONE,
      &GPIO02_SERVICE,
      &GPIO02_MODE_CHARACTERISTIC,
      &GPIO02_DATA_CHARACTERISTIC },
    { 03,
      PIN_MODE_NONE,
      &GPIO03_SERVICE,
      &GPIO03_MODE_CHARACTERISTIC,
      &GPIO03_DATA_CHARACTERISTIC },
    { 29,
      PIN_MODE_NONE,
      &GPIO29_SERVICE,
      &GPIO29_MODE_CHARACTERISTIC,
      &GPIO29_DATA_CHARACTERISTIC },
    { 30,
      PIN_MODE_NONE,
      &GPIO30_SERVICE,
      &GPIO30_MODE_CHARACTERISTIC,
      &GPIO30_DATA_CHARACTERISTIC },
    { 31,
      PIN_MODE_NONE,
      &GPIO31_SERVICE,
      &GPIO31_MODE_CHARACTERISTIC,
      &GPIO31_DATA_CHARACTERISTIC },
    { 32,
      PIN_MODE_NONE,
      &GPIO32_SERVICE,
      &GPIO32_MODE_CHARACTERISTIC,
      &GPIO32_DATA_CHARACTERISTIC },
    { 33,
      PIN_MODE_NONE,
      &GPIO33_SERVICE,
      &GPIO33_MODE_CHARACTERISTIC,
      &GPIO33_DATA_CHARACTERISTIC },
    { 34,
      PIN_MODE_NONE,
      &GPIO34_SERVICE,
      &GPIO34_MODE_CHARACTERISTIC,
      &GPIO34_DATA_CHARACTERISTIC },
    { 38,
      PIN_MODE_NONE,
      &GPIO38_SERVICE,
      &GPIO38_MODE_CHARACTERISTIC,
      &GPIO38_DATA_CHARACTERISTIC },
    { 39,
      PIN_MODE_NONE,
      &GPIO39_SERVICE,
      &GPIO39_MODE_CHARACTERISTIC,
      &GPIO39_DATA_CHARACTERISTIC },
    { 57,
      PIN_MODE_NONE,
      &GPIO57_SERVICE,
      &GPIO57_MODE_CHARACTERISTIC,
      &GPIO57_DATA_CHARACTERISTIC },
    { 58,
      PIN_MODE_NONE,
      &GPIO58_SERVICE,
      &GPIO58_MODE_CHARACTERISTIC,
      &GPIO58_DATA_CHARACTERISTIC },
    { 59,
      PIN_MODE_NONE,
      &GPIO59_SERVICE,
      &GPIO59_MODE_CHARACTERISTIC,
      &GPIO59_DATA_CHARACTERISTIC },
    { 60,
      PIN_MODE_NONE,
      &GPIO60_SERVICE,
      &GPIO60_MODE_CHARACTERISTIC,
      &GPIO60_DATA_CHARACTERISTIC },
};

void setup_lble();

#endif
