#include <LBLEPeriphral.h>
#include <LBLE.h>
#include "constants.hpp"
#include "lble_setup.hpp"
#include "Arduino.h"

void setup_lble()
{
    Serial.begin(9600);

    // setup services and characteristics
    PIN02_SERVICE.addAttribute(PIN02_ANALOG_INPUT_CHAR);
    PIN02_SERVICE.addAttribute(PIN02_ANALOG_OUTPUT_CHAR);
    PIN02_SERVICE.addAttribute(PIN02_DIGITAL_INPUT_CHAR);
    PIN02_SERVICE.addAttribute(PIN02_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN02_SERVICE);

    PIN03_SERVICE.addAttribute(PIN03_ANALOG_INPUT_CHAR);
    PIN03_SERVICE.addAttribute(PIN03_ANALOG_OUTPUT_CHAR);
    PIN03_SERVICE.addAttribute(PIN03_DIGITAL_INPUT_CHAR);
    PIN03_SERVICE.addAttribute(PIN03_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN03_SERVICE);

    PIN04_SERVICE.addAttribute(PIN04_ANALOG_INPUT_CHAR);
    PIN04_SERVICE.addAttribute(PIN04_ANALOG_OUTPUT_CHAR);
    PIN04_SERVICE.addAttribute(PIN04_DIGITAL_INPUT_CHAR);
    PIN04_SERVICE.addAttribute(PIN04_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN04_SERVICE);

    PIN05_SERVICE.addAttribute(PIN05_ANALOG_INPUT_CHAR);
    PIN05_SERVICE.addAttribute(PIN05_ANALOG_OUTPUT_CHAR);
    PIN05_SERVICE.addAttribute(PIN05_DIGITAL_INPUT_CHAR);
    PIN05_SERVICE.addAttribute(PIN05_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN05_SERVICE);

    PIN06_SERVICE.addAttribute(PIN06_ANALOG_INPUT_CHAR);
    PIN06_SERVICE.addAttribute(PIN06_ANALOG_OUTPUT_CHAR);
    PIN06_SERVICE.addAttribute(PIN06_DIGITAL_INPUT_CHAR);
    PIN06_SERVICE.addAttribute(PIN06_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN06_SERVICE);

    PIN07_SERVICE.addAttribute(PIN07_ANALOG_INPUT_CHAR);
    PIN07_SERVICE.addAttribute(PIN07_ANALOG_OUTPUT_CHAR);
    PIN07_SERVICE.addAttribute(PIN07_DIGITAL_INPUT_CHAR);
    PIN07_SERVICE.addAttribute(PIN07_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN07_SERVICE);

    PIN08_SERVICE.addAttribute(PIN08_ANALOG_INPUT_CHAR);
    PIN08_SERVICE.addAttribute(PIN08_ANALOG_OUTPUT_CHAR);
    PIN08_SERVICE.addAttribute(PIN08_DIGITAL_INPUT_CHAR);
    PIN08_SERVICE.addAttribute(PIN08_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN08_SERVICE);

    PIN09_SERVICE.addAttribute(PIN09_ANALOG_INPUT_CHAR);
    PIN09_SERVICE.addAttribute(PIN09_ANALOG_OUTPUT_CHAR);
    PIN09_SERVICE.addAttribute(PIN09_DIGITAL_INPUT_CHAR);
    PIN09_SERVICE.addAttribute(PIN09_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN09_SERVICE);

    PIN10_SERVICE.addAttribute(PIN10_ANALOG_INPUT_CHAR);
    PIN10_SERVICE.addAttribute(PIN10_ANALOG_OUTPUT_CHAR);
    PIN10_SERVICE.addAttribute(PIN10_DIGITAL_INPUT_CHAR);
    PIN10_SERVICE.addAttribute(PIN10_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN10_SERVICE);

    PIN11_SERVICE.addAttribute(PIN11_ANALOG_INPUT_CHAR);
    PIN11_SERVICE.addAttribute(PIN11_ANALOG_OUTPUT_CHAR);
    PIN11_SERVICE.addAttribute(PIN11_DIGITAL_INPUT_CHAR);
    PIN11_SERVICE.addAttribute(PIN11_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN11_SERVICE);

    PIN12_SERVICE.addAttribute(PIN12_ANALOG_INPUT_CHAR);
    PIN12_SERVICE.addAttribute(PIN12_ANALOG_OUTPUT_CHAR);
    PIN12_SERVICE.addAttribute(PIN12_DIGITAL_INPUT_CHAR);
    PIN12_SERVICE.addAttribute(PIN12_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN12_SERVICE);

    PIN13_SERVICE.addAttribute(PIN13_ANALOG_INPUT_CHAR);
    PIN13_SERVICE.addAttribute(PIN13_ANALOG_OUTPUT_CHAR);
    PIN13_SERVICE.addAttribute(PIN13_DIGITAL_INPUT_CHAR);
    PIN13_SERVICE.addAttribute(PIN13_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN13_SERVICE);

    PIN14_SERVICE.addAttribute(PIN14_ANALOG_INPUT_CHAR);
    PIN14_SERVICE.addAttribute(PIN14_ANALOG_OUTPUT_CHAR);
    PIN14_SERVICE.addAttribute(PIN14_DIGITAL_INPUT_CHAR);
    PIN14_SERVICE.addAttribute(PIN14_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN14_SERVICE);

    PIN15_SERVICE.addAttribute(PIN15_ANALOG_INPUT_CHAR);
    PIN15_SERVICE.addAttribute(PIN15_ANALOG_OUTPUT_CHAR);
    PIN15_SERVICE.addAttribute(PIN15_DIGITAL_INPUT_CHAR);
    PIN15_SERVICE.addAttribute(PIN15_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN15_SERVICE);

    PIN16_SERVICE.addAttribute(PIN16_ANALOG_INPUT_CHAR);
    PIN16_SERVICE.addAttribute(PIN16_ANALOG_OUTPUT_CHAR);
    PIN16_SERVICE.addAttribute(PIN16_DIGITAL_INPUT_CHAR);
    PIN16_SERVICE.addAttribute(PIN16_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN16_SERVICE);

    PIN17_SERVICE.addAttribute(PIN17_ANALOG_INPUT_CHAR);
    PIN17_SERVICE.addAttribute(PIN17_ANALOG_OUTPUT_CHAR);
    PIN17_SERVICE.addAttribute(PIN17_DIGITAL_INPUT_CHAR);
    PIN17_SERVICE.addAttribute(PIN17_DIGITAL_OUTPUT_CHAR);
    LBLEPeripheral.addService(PIN17_SERVICE);

    LBLE.begin();
    while(!LBLE.ready())
        delay(100);
    Serial.println("BLE ready.");

    Serial.print("MAC address: ");
    Serial.println(LBLE.getDeviceAddress());

    // advertise
    LBLEAdvertisementData advertisement;
    advertisement.configAsConnectableDevice(DEVICE_NAME);
    LBLEPeripheral.setName(DEVICE_NAME);

    LBLEPeripheral.begin();
    LBLEPeripheral.advertise(advertisement);
}
