#ifndef __MT7697_LBLE_CONFIG_HPP__
#define __MT7697_LBLE_CONFIG_HPP__

#include <vector>
#include <LBLEPeriphral.h>
#include <LBLE.h>

const int PIN_MODE_ANALOG_READ   = 0x00;
const int PIN_MODE_ANALOG_WRITE  = 0x01;
const int PIN_MODE_DIGITAL_READ  = 0x02;
const int PIN_MODE_DIGITAL_WRITE = 0x03;
const int PIN_MODE_SERVO         = 0x04;
const int PIN_MODE_NONE          = 0xFF;

// pin profile struct
struct pin_lble_profile
{
    int pin;
    int mode;
    LBLEService *service;
    LBLECharacteristicInt *analog_input_char;
    LBLECharacteristicInt *analog_output_char;
    LBLECharacteristicInt *digital_input_char;
    LBLECharacteristicInt *digital_output_char;
};

// TODO I2C impl.
/*
LBLEService I2C_SERVICE();
LBLECharacteristicInt I2C_READ_CHARACTERISTIC();
LBLECharacteristicInt I2C_WRITE_CHARACTERISTIC();
*/

static LBLEService            PIN02_SERVICE            (PIN02_SERVICE_UUID);
static LBLECharacteristicInt  PIN02_ANALOG_INPUT_CHAR  (PIN02_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN02_ANALOG_OUTPUT_CHAR (PIN02_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN02_DIGITAL_INPUT_CHAR (PIN02_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN02_DIGITAL_OUTPUT_CHAR(PIN02_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService            PIN03_SERVICE            (PIN03_SERVICE_UUID);
static LBLECharacteristicInt  PIN03_ANALOG_INPUT_CHAR  (PIN03_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN03_ANALOG_OUTPUT_CHAR (PIN03_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN03_DIGITAL_INPUT_CHAR (PIN03_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN03_DIGITAL_OUTPUT_CHAR(PIN03_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService            PIN04_SERVICE            (PIN04_SERVICE_UUID);
static LBLECharacteristicInt  PIN04_ANALOG_INPUT_CHAR  (PIN04_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN04_ANALOG_OUTPUT_CHAR (PIN04_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN04_DIGITAL_INPUT_CHAR (PIN04_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN04_DIGITAL_OUTPUT_CHAR(PIN04_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService            PIN05_SERVICE            (PIN05_SERVICE_UUID);
static LBLECharacteristicInt  PIN05_ANALOG_INPUT_CHAR  (PIN05_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN05_ANALOG_OUTPUT_CHAR (PIN05_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN05_DIGITAL_INPUT_CHAR (PIN05_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN05_DIGITAL_OUTPUT_CHAR(PIN05_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService            PIN06_SERVICE            (PIN06_SERVICE_UUID);
static LBLECharacteristicInt  PIN06_ANALOG_INPUT_CHAR  (PIN06_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN06_ANALOG_OUTPUT_CHAR (PIN06_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN06_DIGITAL_INPUT_CHAR (PIN06_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN06_DIGITAL_OUTPUT_CHAR(PIN06_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService            PIN07_SERVICE            (PIN07_SERVICE_UUID);
static LBLECharacteristicInt  PIN07_ANALOG_INPUT_CHAR  (PIN07_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN07_ANALOG_OUTPUT_CHAR (PIN07_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN07_DIGITAL_INPUT_CHAR (PIN07_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN07_DIGITAL_OUTPUT_CHAR(PIN07_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService            PIN08_SERVICE            (PIN08_SERVICE_UUID);
static LBLECharacteristicInt  PIN08_ANALOG_INPUT_CHAR  (PIN08_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN08_ANALOG_OUTPUT_CHAR (PIN08_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN08_DIGITAL_INPUT_CHAR (PIN08_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN08_DIGITAL_OUTPUT_CHAR(PIN08_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService            PIN09_SERVICE            (PIN09_SERVICE_UUID);
static LBLECharacteristicInt  PIN09_ANALOG_INPUT_CHAR  (PIN09_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN09_ANALOG_OUTPUT_CHAR (PIN09_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN09_DIGITAL_INPUT_CHAR (PIN09_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN09_DIGITAL_OUTPUT_CHAR(PIN09_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService            PIN10_SERVICE            (PIN10_SERVICE_UUID);
static LBLECharacteristicInt  PIN10_ANALOG_INPUT_CHAR  (PIN10_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN10_ANALOG_OUTPUT_CHAR (PIN10_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN10_DIGITAL_INPUT_CHAR (PIN10_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN10_DIGITAL_OUTPUT_CHAR(PIN10_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService            PIN11_SERVICE            (PIN11_SERVICE_UUID);
static LBLECharacteristicInt  PIN11_ANALOG_INPUT_CHAR  (PIN11_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN11_ANALOG_OUTPUT_CHAR (PIN11_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN11_DIGITAL_INPUT_CHAR (PIN11_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN11_DIGITAL_OUTPUT_CHAR(PIN11_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService            PIN12_SERVICE            (PIN12_SERVICE_UUID);
static LBLECharacteristicInt  PIN12_ANALOG_INPUT_CHAR  (PIN12_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN12_ANALOG_OUTPUT_CHAR (PIN12_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN12_DIGITAL_INPUT_CHAR (PIN12_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN12_DIGITAL_OUTPUT_CHAR(PIN12_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService            PIN13_SERVICE            (PIN13_SERVICE_UUID);
static LBLECharacteristicInt  PIN13_ANALOG_INPUT_CHAR  (PIN13_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN13_ANALOG_OUTPUT_CHAR (PIN13_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN13_DIGITAL_INPUT_CHAR (PIN13_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN13_DIGITAL_OUTPUT_CHAR(PIN13_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService            PIN14_SERVICE            (PIN14_SERVICE_UUID);
static LBLECharacteristicInt  PIN14_ANALOG_INPUT_CHAR  (PIN14_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN14_ANALOG_OUTPUT_CHAR (PIN14_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN14_DIGITAL_INPUT_CHAR (PIN14_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN14_DIGITAL_OUTPUT_CHAR(PIN14_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService            PIN15_SERVICE            (PIN15_SERVICE_UUID);
static LBLECharacteristicInt  PIN15_ANALOG_INPUT_CHAR  (PIN15_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN15_ANALOG_OUTPUT_CHAR (PIN15_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN15_DIGITAL_INPUT_CHAR (PIN15_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN15_DIGITAL_OUTPUT_CHAR(PIN15_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService            PIN16_SERVICE            (PIN16_SERVICE_UUID);
static LBLECharacteristicInt  PIN16_ANALOG_INPUT_CHAR  (PIN16_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN16_ANALOG_OUTPUT_CHAR (PIN16_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN16_DIGITAL_INPUT_CHAR (PIN16_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN16_DIGITAL_OUTPUT_CHAR(PIN16_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);

static LBLEService            PIN17_SERVICE            (PIN17_SERVICE_UUID);
static LBLECharacteristicInt  PIN17_ANALOG_INPUT_CHAR  (PIN17_ANALOG_INPUT_CHAR_UUID,   LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN17_ANALOG_OUTPUT_CHAR (PIN17_ANALOG_OUTPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN17_DIGITAL_INPUT_CHAR (PIN17_DIGITAL_INPUT_CHAR_UUID,  LBLE_READ | LBLE_WRITE);
static LBLECharacteristicInt  PIN17_DIGITAL_OUTPUT_CHAR(PIN17_DIGITAL_OUTPUT_CHAR_UUID, LBLE_READ | LBLE_WRITE);


static pin_lble_profile PIN_LBLE_PROFILES[] = {
    int pin;
    int mode;
    LBLEService *service;
    LBLECharacteristicInt *analog_input_char;
    LBLECharacteristicInt *analog_output_char;
    LBLECharacteristicInt *digital_input_char;
    LBLECharacteristicInt *digital_output_char;

    { 2,
      PIN_MODE_NONE,
      &PIN02_SERVICE, 
      &PIN02_ANALOG_INPUT_CHAR,
      &PIN02_ANALOG_OUTPUT_CHAR, 
      &PIN02_DIGITAL_INPUT_CHAR, 
      &PIN02_DIGITAL_OUTPUT_CHAR },
    { 3,
      PIN_MODE_NONE,
      &PIN03_SERVICE, 
      &PIN03_ANALOG_INPUT_CHAR,
      &PIN03_ANALOG_OUTPUT_CHAR, 
      &PIN03_DIGITAL_INPUT_CHAR, 
      &PIN03_DIGITAL_OUTPUT_CHAR },
    { 4,
      PIN_MODE_NONE,
      &PIN04_SERVICE, 
      &PIN04_ANALOG_INPUT_CHAR,
      &PIN04_ANALOG_OUTPUT_CHAR, 
      &PIN04_DIGITAL_INPUT_CHAR, 
      &PIN04_DIGITAL_OUTPUT_CHAR },
    { 5,
      PIN_MODE_NONE,
      &PIN05_SERVICE, 
      &PIN05_ANALOG_INPUT_CHAR,
      &PIN05_ANALOG_OUTPUT_CHAR, 
      &PIN05_DIGITAL_INPUT_CHAR, 
      &PIN05_DIGITAL_OUTPUT_CHAR },
    { 7,
      PIN_MODE_NONE,
      &PIN07_SERVICE, 
      &PIN07_ANALOG_INPUT_CHAR,
      &PIN07_ANALOG_OUTPUT_CHAR, 
      &PIN07_DIGITAL_INPUT_CHAR, 
      &PIN07_DIGITAL_OUTPUT_CHAR },
    { 8,
      PIN_MODE_NONE,
      &PIN08_SERVICE, 
      &PIN08_ANALOG_INPUT_CHAR,
      &PIN08_ANALOG_OUTPUT_CHAR, 
      &PIN08_DIGITAL_INPUT_CHAR, 
      &PIN08_DIGITAL_OUTPUT_CHAR },
    { 2,
      PIN_MODE_NONE,
      &PIN09_SERVICE, 
      &PIN09_ANALOG_INPUT_CHAR,
      &PIN09_ANALOG_OUTPUT_CHAR, 
      &PIN09_DIGITAL_INPUT_CHAR, 
      &PIN09_DIGITAL_OUTPUT_CHAR },
    { 2,
      PIN_MODE_NONE,
      &PIN02_SERVICE, 
      &PIN02_ANALOG_INPUT_CHAR,
      &PIN02_ANALOG_OUTPUT_CHAR, 
      &PIN02_DIGITAL_INPUT_CHAR, 
      &PIN02_DIGITAL_OUTPUT_CHAR },
    { 2,
      PIN_MODE_NONE,
      &PIN02_SERVICE, 
      &PIN02_ANALOG_INPUT_CHAR,
      &PIN02_ANALOG_OUTPUT_CHAR, 
      &PIN02_DIGITAL_INPUT_CHAR, 
      &PIN02_DIGITAL_OUTPUT_CHAR },
    { 2,
      PIN_MODE_NONE,
      &PIN02_SERVICE, 
      &PIN02_ANALOG_INPUT_CHAR,
      &PIN02_ANALOG_OUTPUT_CHAR, 
      &PIN02_DIGITAL_INPUT_CHAR, 
      &PIN02_DIGITAL_OUTPUT_CHAR },
    { 2,
      PIN_MODE_NONE,
      &PIN02_SERVICE, 
      &PIN02_ANALOG_INPUT_CHAR,
      &PIN02_ANALOG_OUTPUT_CHAR, 
      &PIN02_DIGITAL_INPUT_CHAR, 
      &PIN02_DIGITAL_OUTPUT_CHAR },
    { 2,
      PIN_MODE_NONE,
      &PIN02_SERVICE, 
      &PIN02_ANALOG_INPUT_CHAR,
      &PIN02_ANALOG_OUTPUT_CHAR, 
      &PIN02_DIGITAL_INPUT_CHAR, 
      &PIN02_DIGITAL_OUTPUT_CHAR },
    { 2,
      PIN_MODE_NONE,
      &PIN02_SERVICE, 
      &PIN02_ANALOG_INPUT_CHAR,
      &PIN02_ANALOG_OUTPUT_CHAR, 
      &PIN02_DIGITAL_INPUT_CHAR, 
      &PIN02_DIGITAL_OUTPUT_CHAR },
    { 9,
      PIN_MODE_NONE,
      &PIN02_SERVICE, 
      &PIN02_ANALOG_INPUT_CHAR,
      &PIN02_ANALOG_OUTPUT_CHAR, 
      &PIN02_DIGITAL_INPUT_CHAR, 
      &PIN02_DIGITAL_OUTPUT_CHAR },
    { 10,
      PIN_MODE_NONE,
      &PIN10_SERVICE, 
      &PIN10_ANALOG_INPUT_CHAR,
      &PIN10_ANALOG_OUTPUT_CHAR, 
      &PIN10_DIGITAL_INPUT_CHAR, 
      &PIN10_DIGITAL_OUTPUT_CHAR },
    { 11,
      PIN_MODE_NONE,
      &PIN11_SERVICE, 
      &PIN11_ANALOG_INPUT_CHAR,
      &PIN11_ANALOG_OUTPUT_CHAR, 
      &PIN11_DIGITAL_INPUT_CHAR, 
      &PIN11_DIGITAL_OUTPUT_CHAR },
    { 12,
      PIN_MODE_NONE,
      &PIN12_SERVICE, 
      &PIN12_ANALOG_INPUT_CHAR,
      &PIN12_ANALOG_OUTPUT_CHAR, 
      &PIN12_DIGITAL_INPUT_CHAR, 
      &PIN12_DIGITAL_OUTPUT_CHAR },
    { 13,
      PIN_MODE_NONE,
      &PIN13_SERVICE, 
      &PIN13_ANALOG_INPUT_CHAR,
      &PIN13_ANALOG_OUTPUT_CHAR, 
      &PIN13_DIGITAL_INPUT_CHAR, 
      &PIN13_DIGITAL_OUTPUT_CHAR },
    { 14,
      PIN_MODE_NONE,
      &PIN14_SERVICE, 
      &PIN14_ANALOG_INPUT_CHAR,
      &PIN14_ANALOG_OUTPUT_CHAR, 
      &PIN14_DIGITAL_INPUT_CHAR, 
      &PIN14_DIGITAL_OUTPUT_CHAR },
    { 15,
      PIN_MODE_NONE,
      &PIN15_SERVICE, 
      &PIN15_ANALOG_INPUT_CHAR,
      &PIN15_ANALOG_OUTPUT_CHAR, 
      &PIN15_DIGITAL_INPUT_CHAR, 
      &PIN15_DIGITAL_OUTPUT_CHAR },
    { 16,
      PIN_MODE_NONE,
      &PIN16_SERVICE, 
      &PIN16_ANALOG_INPUT_CHAR,
      &PIN16_ANALOG_OUTPUT_CHAR, 
      &PIN16_DIGITAL_INPUT_CHAR, 
      &PIN16_DIGITAL_OUTPUT_CHAR },
    { 17,
      PIN_MODE_NONE,
      &PIN17_SERVICE, 
      &PIN17_ANALOG_INPUT_CHAR,
      &PIN17_ANALOG_OUTPUT_CHAR, 
      &PIN17_DIGITAL_INPUT_CHAR, 
      &PIN17_DIGITAL_OUTPUT_CHAR },
};

void setup_lble();

#endif
